CREATE TABLE animal (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(40) NOT NULL,
   specie VARCHAR(40) NOT NULL,
   age INT NOT NULL,
   breed VARCHAR(40) NOT NULL,
   input_date date NOT NULL,
   adoption_date date,
   observation VARCHAR(255) NOT NULL,
   caretaker VARCHAR(40) NOT NULL,
   death_date date,
   size ENUM('SMALL', 'MEDIUM', 'LARGE') NOT NULL,
   CONSTRAINT pk_animal PRIMARY KEY (id)
);

CREATE TABLE caretaker (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(40) NOT NULL,
   contact VARCHAR(40) NOT NULL,
   age INT NOT NULL,
   contract_start date NOT NULL,
   contract_end date,
   CONSTRAINT pk_caretaker PRIMARY KEY (id)
);